version: '2'
services:
    samplepms-app:
        image: samplepms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samplepms-mysql:3306/samplepms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=samplepms-elasticsearch:9300
        ports:
            - 8080:8080
    samplepms-mysql:
        extends:
            file: mysql.yml
            service: samplepms-mysql
    samplepms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: samplepms-elasticsearch
